### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by sirthxalot** [sta-laravel/skeleton#1]
## Summary

At this point we will have an empty project ready to get feed with some data. So lets beginn to tackle down the default structure of our application and prepare everything in order to get ready for the real development.

## Tasks

- [x] Add common project files.
- [x] Build a skeleton application based on the Laravel 5.3 PHP Framework.
- [x] Add [Laravel IDE Helper](https://github.com/barryvdh/laravel-ide-helper) Extension.
- [x] Add [Laracasts Generators](https://github.com/laracasts/Laravel-5-Generators-Extended) Extension.
- [x] Add [Laracasts Test Dummy](https://github.com/laracasts/TestDummy) Extension.
- [x] Refactor default phpunit test provided by the Skeleton Application.
- [x] Refactor every single file from the default framework in order to fit the coding standards.
- [x] Setup testing environment, in order to run on Travis CI runners.
